Add Mobile Menu Implementation
ahmidou09/my-Portfolio pull request #12
Opened 2023-06-19 21:27 UTC by ahmidou09

This pull request adds the implementation of the mobile menu functionality to the portfolio website.
The mobile menu allows users to interact with the menu by clicking or tapping the hamburger button to make the menu appear, clicking or tapping the close (X) button to make the menu disappear, and selecting any of the mobile menu options to hide the menu and display the corresponding part of the page. The implementation adheres to the provided design templates and follows the best practices for HTML, CSS, and JavaScript.
Additionally, a JavaScript, HTML, and CSS linter has been added to ensure code quality.

2023-06-19 23:14 UTC, LionRouge1 requested changes
Hi **Team**, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- Good job implementing the mobile menu it working fine :1st_place_medal: 
- Nice work following JavaScript and HTML & CSS best practices :100:  
- All linters passed :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-19 23:14 UTC, LionRouge1 commented on index.html
>            </ul>
- [ ] Nice work implementing the mobile menu :clap: :sunglasses: However It would be nice to stick to the Figma design as requested in the project requirement (e.g., font, colors, images, text, margins). Therefore I suggest you use the same `font-size`, `font-weight` and margin between the menu options as in the Figma design.
### Your design :point_down: 
![Screenshot from 2023-06-19 22-50-19](https://github.com/ahmidou09/my-Portfolio/assets/91142432/0730b85f-0b53-4fe2-b7b3-a3a4c18b9452)
### What it's supposed to look like :point_down: 
![Screenshot from 2023-06-19 23-05-57](https://github.com/ahmidou09/my-Portfolio/assets/91142432/8633082e-2840-460d-969c-a02c12a55721)

2023-06-19 23:14 UTC, LionRouge1 commented on style.css
>  }
- [ ] Kindly note the background color and the transparency design of the mobile menu on the Figma design and make sure your mobile menu looks identical to it, to follow the project requirement.
### Your design :point_down: 
![Screenshot from 2023-06-19 23-05-01](https://github.com/ahmidou09/my-Portfolio/assets/91142432/02fa846d-95aa-463f-986e-20b19a1d3c2a)
### What it's supposed to look like :point_down: 
![Screenshot from 2023-05-15 17-26-08](https://github.com/ahmidou09/my-Portfolio/assets/91142432/7526e3ef-b8fc-4cfc-a3ab-5bcdd709f207)

2023-06-20 00:15 UTC, LionRouge1 approved these changes
Hi **Team**, 

# STATUS: APPROVED! 🥇 💯 
Great work on making the changes 👏 
You've done well implementing the requested changes

![done](https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif)

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-06-20 00:15 UTC, LionRouge1 commented on style.css
> +}
[OPTIONAL]
- [ ] Nice work making the changes :+1: However it would be nice to add `position: fixed` to the `.nav` class to prevent it scroll with the page.

2023-06-20 00:23 UTC, ahmidou09 commented on style.css
> +}
Well, thanks for your valuable remark

2023-06-20 00:24 UTC, ahmidou09 commented on style.css
> +}
Ok, thanks for your valuable remark.

2023-06-20 00:32 UTC, merged