Implement desktop styling based on Figma template design
ahmidou09/my-Portfolio pull request #5
Opened 2023-06-07 21:26 UTC by ahmidou09

This pull request includes the implementation of desktop styling for the project.
The goal is to replicate the design as closely as possible, including the layout, fonts, colors, images, text, and margins specified in the Figma template.
Media queries have been used in the CSS file to ensure that the desktop version matches the selected template (Desktop: >=768px).
The layout elements have been organized using Grid and Flexbox for optimal arrangement.

2023-06-07 22:16 UTC, tufoinnkuo10 requested changes
Hi @ahmidou09 
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ followed figma design

Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/Q1r6trHMbDtGaUpofD/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-06-07 22:16 UTC, tufoinnkuo10 commented on index.html
> +              <button type="button" class="btn-primary">See project</button>
- [ ] Great job with the media query and making your work responsive. Please kindly reduce the margin left and right so it matches the design. See the difference below. kindly implement this till the contact section.
yours
![Screenshot (1110)_LI](https://github.com/ahmidou09/my-Portfolio/assets/65298048/974ca1de-51c2-451b-9aa0-0cb42dc286de)
figma
![Screenshot (1111)](https://github.com/ahmidou09/my-Portfolio/assets/65298048/717c215b-9f9f-4df0-91dd-979d27744060)

2023-06-07 22:16 UTC, tufoinnkuo10 commented on index.html
> +            <p class="form-para">
- [ ] Great job. please note that the contact section is full width. kindly fix this to align with the figma design.
yours
![Screenshot (1108)_LI](https://github.com/ahmidou09/my-Portfolio/assets/65298048/0fd09e55-f240-4c92-a715-a42689218f96)
figma
![Screenshot (1109)](https://github.com/ahmidou09/my-Portfolio/assets/65298048/f1afe5cd-59e4-41e5-89e0-1ed0b4827b0c)

2023-06-07 22:16 UTC, tufoinnkuo10 commented on index.html
> +              <button type="button" class="btn-primary">See project</button>
- [ ] please kindly ensure the desktop version has the button interaction of hover and pressed like the original design.
![Screenshot (1112)](https://github.com/ahmidou09/my-Portfolio/assets/65298048/bc856f47-aa2a-427a-9a76-b2e666c822ed)

2023-06-08 00:18 UTC, Owusu-Desmond approved these changes
Hi @ahmidou09 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 00:18 UTC, Owusu-Desmond commented on style.css
> +
- [ OPTIONAL ] Please make sure that the About section matches the Figma design, the list languages should align right on the desktop screen as you can see below :point_down: 

  ### YOUR DESIGN
  ![image](https://github.com/ahmidou09/my-Portfolio/assets/92303891/13ddc0b5-23fd-4ca1-b677-20b8dc7d6ed7)
  
  ### FIGMA DESIGN
  ![image](https://github.com/ahmidou09/my-Portfolio/assets/92303891/cc366ec2-7364-4169-8339-8dec8b803d47)

2023-06-08 00:33 UTC, ahmidou09 commented on style.css
> +
ok thank you

2023-06-08 00:33 UTC, merged